### PR TITLE
event creation fixes without end date #30

### LINKED ISSUE #30: Error while creating an event in CiviCRM
Create an event in CiviCRM by entering required fields and it throws below error.

 **Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
DateTime::__construct(): Failed to parse time string (null) at position 0 (n): The timezone could not be found in the database
Return to home page.**

Below is the backtrace.

```
Feb 02 19:04:09  [error] 
$Fatal Error Details = array:3 [
  "message" => "DateTime::__construct(): Failed to parse time string (null) at position 0 (n): The timezone could not be found in the database"
  "code" => null
  "exception" => Exception {#9274
    #message: "DateTime::__construct(): Failed to parse time string (null) at position 0 (n): The timezone could not be found in the database"
    #code: 0
    #file: "/var/www/html/wp-content/plugins/civicrm-event-organiser/includes/civicrm-event-organiser-eo.php"
    #line: 439
    +"severity": 2
    trace: {
      /var/www/html/wp-content/plugins/civicrm-event-organiser/includes/civicrm-event-organiser-eo.php:439 {
        <E2><80><BA> // End date and end of schedule are the same.
        <E2><80><BA> 'end' => new DateTime( $civi_event['end_date'], eo_get_blog_timezone() ),
        <E2><80><BA> 'schedule_last' => new DateTime( $civi_event['end_date'], eo_get_blog_timezone() ),
        arguments: {
          $time: "null"
          $timezone: DateTimeZone {#9269 <E2><80><A6>}
        }
      }
      /var/www/html/wp-content/plugins/civicrm-event-organiser/includes/civicrm-event-organiser-civi.php:208 { <E2><80><A6>}
      /var/www/html/wp-includes/class-wp-hook.php:287 { <E2><80><A6>}
      /var/www/html/wp-includes/class-wp-hook.php:311 { <E2><80><A6>}
      /var/www/html/wp-includes/plugin.php:551 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php:108 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php:180 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php:214 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php:44 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php:129 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php:366 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Event/BAO/Event.php:90 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Event/BAO/Event.php:128 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Event/Form/ManageEvent/EventInfo.php:250 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php:514 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php:152 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php:119 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php:203 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php:103 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php:347 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php:98 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:285 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:68 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { <E2><80><A6>}
      /var/www/html/wp-content/plugins/civicrm/civicrm.php:1649 { <E2><80><A6>}
      /var/www/html/wp-includes/class-wp-hook.php:287 { <E2><80><A6>}
      /var/www/html/wp-includes/class-wp-hook.php:311 { <E2><80><A6>}
      /var/www/html/wp-includes/plugin.php:484 { <E2><80><A6>}
      /var/www/html/wp-admin/admin.php:259 { <E2><80><A6>}
    }
  }
]


Feb 02 19:04:09  [debug] $backTrace = #0 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(433): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(Exception))
#2 /var/www/html/wp-content/plugins/civicrm/civicrm.php(1649): CRM_Core_Invoke::invoke((Array:3))
#3 /var/www/html/wp-includes/class-wp-hook.php(287): CiviCRM_For_WordPress->invoke("")
#4 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters("", (Array:1))
#5 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action((Array:1))
#6 /var/www/html/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#7 {main}

```

Note that timezone is selected in WordPress. It is UTC+0

### PR DESCRIPTION
**Pull request by kurund**
Fixes #30

### CODE REVIEW

**Comment by christianwach** [comment]
@kurund Thanks for this. I see this involves that weird CiviCRM `null` string... does that mean that `$civi_event['end_date']` is never an actual `NULL` or `empty()`?

**Comment by kurund** [comment]
@christianwach yes, it is weird and CiviCRM passes 'null' string hence was not able to use `empty()`. I think internal date handling in CiviCRM takes care of this.

**Comment by christianwach** [comment]
@kurund Okay, I'll do some tests with events that have no end date and will merge if I can trace where CiviCRM specifies the `null` string.

**Comment by christianwach** [comment]
@kurund So, I've confirmed that the value is `(str) "null"` on `create` but it seems that there are going to have to be more comprehensive checks on `$civi_event['end_date']`. Once the fatal error has happened (or your code has caught it) I still get:

`PHP Notice:  Undefined index: end_date`

when I re-save the CiviEvent with no end date. 

The `civicrm_post` hook can be a PITA because it often only includes data that was present in the save operation - and therefore, in the case of `edit` operations, it's missing from the array. I'd recommend checking `$civi_event['end_date']` for `empty()` or `(str) "null"` as you do at present. That should cover all bases.

**Comment by christianwach** [comment]
@kurund One more thing to consider - EO simply copies the "start time" into the "end time" fields when "end time" is missing:

Screenshot 2021-02-16 at 15 12 10

I don't know if this has an impact elsewhere, though as far as I can tell EO seems fairly robust when it displays the event as a page or in the calendar. Just thought I'd leave this here for reference.

**Comment by christianwach** [comment]
Resolved via 41ad4cc462fa0cdf934614b75f5e05d3e39c844f

**Comment by kurund** [comment]
@christianwach yes, I don't see this having an impact in other places. Thank you for the fix.

**Pull request closed without merging**
